CREATE DATABASE IF NOT EXISTS ATMOSYNC_DB;

CREATE SCHEMA IF NOT EXISTS ATMOSYNC_DB.TELEMETRY_SCHEMA;

CREATE TABLE IF NOT EXISTS ATMOSYNC_DB.TELEMETRY_SCHEMA.RAW_TELEMETRY (
    container_id VARCHAR NOT NULL,
    timestamp TIMESTAMP_NTZ NOT NULL,
    commodity VARCHAR NOT NULL,
    temperature FLOAT,
    humidity FLOAT,
    vibration FLOAT,
    condition VARCHAR
);